---
title: PALD
---

description: Psycholinguistics and Diversity Lab


remote_theme: pages-themes/cayman@v0.2.0 # Establishes a theme
plugins:
- jekyll-remote-theme # when an attribute has multile values, start a new line
